export const TODOLIST_ACTION_SAGA = {
  GET_ALL_TASK_API_SAGA: "GET_ALL_TASK_API",
  ADD_TASK_API_SAGA: "ADD_TASK_API_SAGA",
  DELETE_TASK_API_SAGA: "DELETE_TASK_API_SAGA",
  CHECK_TASK_API_SAGA: "CHECK_TASK_API_SAGA",
  REJECT_TASK_API_SAGA: "REJECT_TASK_API_SAGA",
};
